//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavajaSuiza {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CadenasTexto {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CadenasTexto() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NavajaSuiza.CadenasTexto", typeof(CadenasTexto).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número introducido no puede contener caracteres no numéricos.
        /// </summary>
        internal static string CaracteresAlfaNum {
            get {
                return ResourceManager.GetString("CaracteresAlfaNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Error!
        ///
        ///.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número introducido debe ser un número positivo mayor que 0.
        /// </summary>
        internal static string MayorQue0 {
            get {
                return ResourceManager.GetString("MayorQue0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número introducido debe ser menor que .
        /// </summary>
        internal static string MenorQue {
            get {
                return ResourceManager.GetString("MenorQue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  no es primo.
        /// </summary>
        internal static string NoPrimo {
            get {
                return ResourceManager.GetString("NoPrimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  no es un número entero correcto
        ///
        ///.
        /// </summary>
        internal static string NumeroIncorrecto {
            get {
                return ResourceManager.GetString("NumeroIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  es primo.
        /// </summary>
        internal static string Primo {
            get {
                return ResourceManager.GetString("Primo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Vacio {
            get {
                return ResourceManager.GetString("Vacio", resourceCulture);
            }
        }
    }
}
